# Documentation line to trigger action
name: Test checkov
on:
  push:
    branches: [ feature-github-action ]
jobs:
  find-jobs:
    name: Find Jobs
    container: debian:buster-slim
    outputs:
      folders: ${{ steps.jobs.outputs.folders }}
    steps:
      - uses: actions/checkout@v1
      - id: jobs
        uses: philips-labs/list-folders-action@v1
        with:
          path: ./path/to/folder

  matrix:
    runs-on: ubuntu-latest
    name: Matrix Jobs
    needs: [find-jobs]
    container: ubuntu
    defaults:
      run:
        working-directory: ${{ matrix.folder }}
    strategy:
      matrix:
        folder: ${{ fromJson(needs.find-jobs.outputs.folders )}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov fmc_access_policies
        uses: bridgecrewio/checkov-action@master
        if: always()
        with:
          directory: ${{ matrix.folder }}
          framework: terraform
  
